[package]
name = "y20d12"
version = "0.1.0"
authors = ["dan <dancrhorton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
helper = { path = "../helper" }
num = "0.4.0"